[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications"
    weight = 2

[[main]]
    identifier = "blog"
    name = "Blog"
    url = "https://xsl.sh/"
    weight = 3
    
# Social Media Configuration

[[social]]
    identifier = "x-twitter"
    name = "X"
    url = "https://twitter.com/0xsling0"
    weight = 1

[[social]]
    identifier = "google-scholar"
    name = "Google Scholar"
    url = "#"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/xslingcn"
    weight = 3