# Basic
title = "Xsling's"
baseURL = "https://xsl.sh/"

# supported languages: en-us, zh-cn (lowercase language codes only)
defaultContentLanguage = 'en-us'
# here lists available languages, if you wish to add your own custom translation, please refer to https://gohugo.io/content-management/multilingual
[languages]
  [languages.en-us]
    languageName = 'English(United States)'
    weight = 20
  [languages.zh-cn]
    languageName = '简体中文（中国大陆）'
    weight = 10

# Pagination
paginate = 10
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 30
    [menu.main.params]
      changeRoute = false
  [[menu.main]]
    name = "Friends"
    identifier = "friends"
    url = "/#/friends"
    weight = 20
    [menu.main.params]
      changeRoute = true
  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    url = "/#/tags"
    weight = 15
    [menu.main.params]
      changeRoute = true
  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/#/blog"
    weight = 10
    [menu.main.params]
      changeRoute = true

[taxonomies]
    tag = "tags"
    
[params]
author = "Xsling"
subtitle = "Oh What a World!"
cdnVersion = "1.1.14"

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = "xsling"

[params.comment]
disqus = ""
duoshuo = ""

[params.comment.gitalk]
enabled = true
repo = "xslingcn.github.io"
owner = "xslingcn"

[params.social]
weibo = ""
github = "xslingcn"
twitter = ""
gplus = ""
telegram = "Xsling"
mail = "me@xsl.sh"
linkedin = "shanli-xing-6b6054240"

[params.ga]
ID = "G-DLFBF98Y4Z"

# The blog button should not be removed.
[params.blogButton]
title = "Blog"
description = "Visit blog"

[params.copyright]
license = 'CC BY-NC-SA 4.0'
license_link = 'http://creativecommons.org/licenses/by-nc-sa/4.0/'

[permalinks]
posts = "/:year/:month/:filename/"
static = "/:filename/"